// Personal InfoSec / IT resource collection.
// Cloned + reorganized from https://start.me/p/0Pq1Le/kaung and extended.
// Each category renders as a card; each link opens in a new tab.

const g = (q) => `https://www.google.com/search?q=${encodeURIComponent(q)}`

export const hubMeta = {
  title: "Collection Hub",
  subtitle: "Personal Bookmarks",
  description:
    "A curated, living collection of the tools, trackers, sandboxes, cheatsheets, and reading lists I actually use day to day in cybersecurity, IT, and DFIR/OSINT work — plus a few things I just find genuinely useful.",
  // Layout/collection this page was cloned from and reorganized out of.
  sourceCredit: {
    label: "Link collection layout adapted from",
    name: "Kaung",
    url: "https://start.me/p/0Pq1Le/kaung",
  },
}

// Featured / pinned resources shown above the grid.
export const featuredResources = [
  {
    title: "Technical Security Certification Roadmap",
    description:
      "210 hands-on cybersecurity certifications across 13 technical domains (pentest, malware RE, cloud, OT/ICS, AI security) — positioned by real depth, not marketing tier.",
    url: "https://certs.pyaeheinnkyaw.com/",
    tag: "Cert Roadmap",
    creditName: "PHK Knowledge Sharing",
    creditUrl: "https://www.pyaeheinnkyaw.com",
  },
]

export const hubCategories = [
  {
    title: "Alerts",
    icon: "AlertTriangle",
    links: [
      { name: "JPCERT Coordination Center", url: "https://www.jpcert.or.jp/english/" },
      { name: "ENISA", url: "https://www.enisa.europa.eu/" },
      { name: "CVE — Common Vulnerabilities and Exposures", url: "https://www.cve.org/" },
      { name: "CVE Details", url: "https://www.cvedetails.com/" },
      { name: "Exploit-DB", url: "https://www.exploit-db.com/" },
    ],
  },
  {
    title: "Blogs",
    icon: "Rss",
    links: [
      { name: "Huntress Blog", url: "https://www.huntress.com/blog" },
      { name: "SANS Internet Storm Center", url: "https://isc.sans.edu/" },
      { name: "Forensic Focus", url: "https://www.forensicfocus.com/" },
    ],
  },
  {
    title: "SOC Tools",
    icon: "Wrench",
    links: [
      { name: "TheresAFewConors/Sooty", url: "https://github.com/TheresAFewConors/Sooty" },
      { name: "Pulsar — network footprint scanner", url: "https://github.com/search?q=pulsar+network+footprint+scanner&type=repositories" },
      { name: "smicallef/spiderfoot", url: "https://github.com/smicallef/spiderfoot" },
      { name: "TheHive-Project/TheHive", url: "https://github.com/TheHive-Project/TheHive" },
      { name: "TheHive-Project/Cortex", url: "https://github.com/TheHive-Project/Cortex" },
      { name: "danieleperera/SocAnalystArsenal", url: "https://github.com/danieleperera/SocAnalystArsenal" },
      { name: "CyberChef", url: "https://gchq.github.io/CyberChef/" },
      { name: "Harpoon (Threat Intel/OSINT)", url: "https://github.com/Te-k/harpoon" },
      { name: "FoxyRecon (OSINT)", url: g("FoxyRecon OSINT tool github") },
      { name: "Domain Analyzer", url: g("Domain_Analyzer github tool") },
      { name: "peepdf — PDF Analysis Tool", url: "https://eternal-todo.com/tools/peepdf-pdf-analysis-tool" },
      { name: "PyREBox — Python scriptable RE sandbox", url: "https://github.com/Cisco-Talos/pyrebox" },
      { name: "OSSEC", url: "https://www.ossec.net/" },
      { name: "Chkrootkit", url: "http://www.chkrootkit.org/" },
      { name: "Process Hacker", url: "https://processhacker.sourceforge.io/" },
      { name: "Wazuh", url: "https://wazuh.com/" },
      { name: "Security Onion Solutions", url: "https://securityonionsolutions.com/" },
      { name: "CAINE Live", url: "https://www.caine-live.net/" },
      { name: "OSSIM — The Open Source SIEM", url: "https://cybersecurity.att.com/products/ossim" },
      { name: "Redline (FireEye/Mandiant)", url: g("FireEye Mandiant Redline download") },
      { name: "MISP", url: "https://www.misp-project.org/" },
      { name: "Mimikatz", url: "https://github.com/gentilkiwi/mimikatz" },
      { name: "Mushy", url: g("mushy tool cybersecurity github") },
    ],
  },
  {
    title: "Frameworks",
    icon: "ShieldCheck",
    links: [
      { name: "MITRE ATT&CK", url: "https://attack.mitre.org/" },
      { name: "D3FEND Matrix", url: "https://d3fend.mitre.org/" },
      { name: "Cyber Kill Chain (Lockheed Martin)", url: "https://www.lockheedmartin.com/en-us/capabilities/cyber/cyber-kill-chain.html" },
      { name: "NIST Cybersecurity Framework", url: "https://www.nist.gov/cyberframework" },
      { name: "Cybersecurity & Infrastructure Security Agency (CISA)", url: "https://www.cisa.gov/" },
      { name: "ISO/IEC 27001", url: "https://www.iso.org/standard/27001" },
      { name: "Health Information Privacy (HIPAA)", url: "https://www.hhs.gov/hipaa/index.html" },
      { name: "GDPR.eu", url: "https://gdpr.eu/" },
    ],
  },
  {
    title: "Hash",
    icon: "KeyRound",
    links: [
      { name: "Hashes.com — Decrypt MD5, SHA1, NTLM, SHA256...", url: "https://hashes.com/en/decrypt/hash" },
      { name: "CrackStation", url: "https://crackstation.net/" },
    ],
  },
  {
    title: "CTFs",
    icon: "Flag",
    links: [
      { name: "CTFtime", url: "https://ctftime.org/" },
      { name: "Hacker101 CTF", url: "https://ctf.hacker101.com/" },
      { name: "picoCTF", url: "https://picoctf.org/" },
      { name: "Google CTF", url: "https://capturetheflag.withgoogle.com/" },
      { name: "GitHub Security Lab — Capture the Flag", url: "https://securitylab.github.com/ctf/" },
      { name: "BelkaCTF", url: "https://belkasoft.com/ctf" },
    ],
  },
  {
    title: "Training Platforms",
    icon: "GraduationCap",
    links: [
      { name: "Blue Team Labs Online", url: "https://blueteamlabs.online/" },
      { name: "CyberDefenders", url: "https://cyberdefenders.org/" },
      { name: "LetsDefend", url: "https://letsdefend.io/" },
      { name: "RangeForce", url: "https://www.rangeforce.com/" },
      { name: "Hack The Box", url: "https://www.hackthebox.com/" },
      { name: "TryHackMe", url: "https://tryhackme.com/" },
      { name: "CyberTalents", url: "https://cybertalents.com/" },
    ],
  },
  {
    title: "Training",
    icon: "BookOpen",
    links: [{ name: "Cyber training resources", url: g("creatiogon cybersecurity training") }],
  },
  {
    title: "Vulnerability Assessment Tools",
    icon: "ShieldAlert",
    links: [
      { name: "Nikto2", url: "https://github.com/sullo/nikto" },
      { name: "OpenVAS", url: "https://www.openvas.org/" },
      { name: "w3af", url: "http://w3af.org/" },
      { name: "Acunetix", url: "https://www.acunetix.com/" },
      { name: "Nmap — the Network Mapper", url: "https://nmap.org/" },
      { name: "Nexpose (Rapid7)", url: "https://www.rapid7.com/products/nexpose/" },
    ],
  },
  {
    title: "POCs",
    icon: "FlaskConical",
    links: [
      { name: "MS-MSDT \"Follina\" POC — JohnHammond", url: "https://github.com/JohnHammond/msdt-follina" },
      { name: "n1shhth/CVE-POC — collection of latest CVE PoCs", url: "https://github.com/n1shhth/CVE-POC" },
    ],
  },
  {
    title: "Bounty Programs",
    icon: "Trophy",
    links: [
      { name: "SOC Prime", url: "https://socprime.com/" },
      { name: "YesWeHack", url: "https://www.yeswehack.com/" },
      { name: "OpenBugBounty", url: "https://www.openbugbounty.org/" },
      { name: "Bugcrowd", url: "https://www.bugcrowd.com/" },
      { name: "SafeHats", url: "https://safehats.com/" },
      { name: "Intigriti", url: "https://www.intigriti.com/" },
      { name: "Synack", url: "https://www.synack.com/" },
    ],
  },
  {
    title: "Certifications",
    icon: "Award",
    links: [
      { name: "GIAC GCIH", url: "https://www.giac.org/certification/certified-incident-handler-gcih" },
      { name: "Blue Team Level 1 (BTL1)", url: "https://blueteamlevel1.com/" },
      { name: "CompTIA CySA+", url: "https://www.comptia.org/certifications/cybersecurity-analyst" },
      { name: "eLearnSecurity (INE)", url: "https://ine.com/learning/certifications" },
      { name: "Mile2", url: "https://mile2.com/" },
      { name: "(ISC)²", url: "https://www.isc2.org/" },
      { name: "Paul Jerimy — Security Certification Roadmap", url: "https://pauljerimy.com/security-certification-roadmap/" },
    ],
  },
  {
    title: "Analysis",
    icon: "Search",
    links: [
      { name: "VirusTotal", url: "https://www.virustotal.com/" },
      { name: "Intezer Analyze", url: "https://analyze.intezer.com/" },
      { name: "Joe Sandbox", url: "https://www.joesandbox.com/" },
      { name: "Any.Run — Interactive Malware Sandbox", url: "https://any.run/" },
      { name: "InQuest Labs", url: "https://labs.inquest.net/" },
      { name: "Hatching Triage", url: "https://tria.ge/" },
      { name: "CAPEv2 Sandbox", url: "https://github.com/kevoreilly/CAPEv2" },
      { name: "FileScan.IO", url: "https://www.filescan.io/" },
      { name: "MalwareBazaar", url: "https://bazaar.abuse.ch/" },
      { name: "Feodo Tracker", url: "https://feodotracker.abuse.ch/" },
      { name: "SSLBL — Malicious SSL Certificates", url: "https://sslbl.abuse.ch/" },
      { name: "ThreatFox", url: "https://threatfox.abuse.ch/" },
      { name: "AbuseIPDB", url: "https://www.abuseipdb.com/" },
      { name: "IPinfo — IP Address API and Data", url: "https://ipinfo.io/" },
      { name: "IBM X-Force Exchange", url: "https://exchange.xforce.ibmcloud.com/" },
      { name: "IPQualityScore", url: "https://www.ipqualityscore.com/" },
      { name: "AlienVault OTX", url: "https://otx.alienvault.com/" },
      { name: "URLhaus", url: "https://urlhaus.abuse.ch/" },
      { name: "urlscan.io — URL and website scanner", url: "https://urlscan.io/" },
      { name: "SecurityTrails", url: "https://securitytrails.com/" },
      { name: "Shodan", url: "https://www.shodan.io/" },
      { name: "IP Geolocation & Fraud Prevention (ipdata)", url: "https://ipdata.co/" },
      { name: "Talos Intelligence — Reputation Center", url: "https://talosintelligence.com/reputation_center" },
      { name: "DomainTools Whois", url: "https://whois.domaintools.com/" },
      { name: "dnstwister", url: "https://dnstwister.report/" },
      { name: "ThreatCrowd", url: "https://www.threatcrowd.org/" },
      { name: "Dig — DNS lookup", url: "https://toolbox.googleapps.com/apps/dig/" },
      { name: "Hunter — email finder", url: "https://hunter.io/" },
      { name: "Email Header Analyzer (Google Admin Toolbox)", url: "https://toolbox.googleapps.com/apps/messageheader/" },
      { name: "RFC822 Header Parser", url: "https://mxtoolbox.com/EmailHeaders.aspx" },
      { name: "Decent Security", url: "https://decentsecurity.com/" },
      { name: "abuse.ch — I Got Phished, Get Notified", url: "https://igotphished.abuse.ch/get-notified/" },
      { name: "YARAify", url: "https://yaraify.abuse.ch/" },
      { name: "Cipher Identifier (dCode)", url: "https://www.dcode.fr/cipher-identifier" },
      { name: "URL2PNG", url: "https://www.url2png.com/" },
      { name: "NirSoft Utilities", url: "https://www.nirsoft.net/" },
      { name: "ExtAnalysis — Tuhinshubhra", url: "https://github.com/Tuhinshubhra/ExtAnalysis" },
      { name: "JSON Crack", url: "https://jsoncrack.com/" },
      { name: "CRXcavator", url: "https://crxcavator.io/" },
      { name: "dnsdumpster", url: "https://dnsdumpster.com/" },
      { name: "Sucuri SiteCheck", url: "https://sitecheck.sucuri.net/" },
      { name: "Where's It Up — API", url: "https://wheresitup.com/" },
      { name: "PhishTank", url: "https://phishtank.org/" },
      { name: "CheckPhish", url: "https://checkphish.ai/" },
      { name: "Censys", url: "https://search.censys.io/" },
      { name: "IPVOID", url: "https://www.ipvoid.com/" },
      { name: "Comodo Valkyrie", url: "https://valkyrie.comodo.com/" },
      { name: "Talos File Reputation", url: "https://talosintelligence.com/talos_file_reputation" },
      { name: "abelcheung/rifiuti2", url: "https://github.com/abelcheung/rifiuti2" },
      { name: "WADComs", url: "https://wadcoms.github.io/" },
      { name: "persistence-info.github.io", url: "https://persistence-info.github.io/" },
      { name: "Unprotect Project", url: "https://unprotect.it/" },
      { name: "LOLBAS", url: "https://lolbas-project.github.io/" },
      { name: "LOLDrivers", url: "https://www.loldrivers.io/" },
      { name: "GTFOBins", url: "https://gtfobins.github.io/" },
      { name: "LOTS Project", url: "https://lots-project.com/" },
      { name: "Filesec.io", url: "https://filesec.io/" },
      { name: "MalAPI.io", url: "https://malapi.io/" },
      { name: "HijackLibs", url: "https://hijacklibs.net/" },
      { name: "Malpedia", url: "https://malpedia.caad.fkie.fraunhofer.de/" },
      { name: "urlquery.net", url: "https://urlquery.net/" },
      { name: "DocGuard", url: "https://www.docguard.io/" },
      { name: "URLVoid", url: "https://www.urlvoid.com/" },
      { name: "Palo Alto Networks — URL Filtering Test", url: "https://urlfiltering.paloaltonetworks.com/" },
      { name: "Device Hunt", url: "https://devicehunt.com/" },
      { name: "Hash Type Identifier", url: "https://www.tunnelsup.com/hash-analyzer/" },
      { name: "WhatIsMyIP — IP/WHOIS Lookup", url: "https://www.whatismyip.com/ip-whois-lookup/" },
      { name: "DNS Checker", url: "https://dnschecker.org/" },
      { name: "Recorded Future — Cyber Threat Intelligence", url: "https://www.recordedfuture.com/" },
      { name: "VPN & Proxy Detection (IPQS)", url: "https://www.ipqualityscore.com/threat-ip-lookup" },
      { name: "ALEAPP — Android Logs Events Parser", url: "https://github.com/abrignoni/ALEAPP" },
      { name: "iLEAPP — iOS Logs, Events, Plists Parser", url: "https://github.com/abrignoni/iLEAPP" },
    ],
  },
  {
    title: "Network",
    icon: "Network",
    links: [
      { name: "Wireshark", url: "https://www.wireshark.org/" },
      { name: "TCPDUMP/LIBPCAP public repository", url: "https://www.tcpdump.org/" },
    ],
  },
  {
    title: "Portals",
    icon: "LayoutGrid",
    links: [{ name: "CFReDS — NIST", url: "https://cfreds.nist.gov/" }],
  },
  {
    title: "Cheatsheet",
    icon: "ClipboardList",
    links: [
      { name: "DFIR Cheatsheet — Jai Minton", url: "https://www.jaiminton.com/cheatsheet/DFIR/" },
      { name: "Bash Scripting Cheatsheet", url: "https://devhints.io/bash" },
      { name: "Active Directory Exploitation Cheat Sheet", url: "https://github.com/S1ckB0y1337/Active-Directory-Exploitation-Cheat-Sheet" },
      { name: "Hacking Tools Cheat Sheet", url: "https://github.com/coreb1t/awesome-pentest-cheat-sheets" },
      { name: "Linux Command Line Forensics & Intrusion Detection", url: g("linux command line forensics and intrusion detection cheat sheet") },
      { name: "Nmap Cheat Sheet", url: "https://www.stationx.net/nmap-cheat-sheet/" },
      { name: "Wireshark Cheat Sheet", url: "https://packetlife.net/media/library/13/Wireshark_Display_Filters.pdf" },
      { name: "Metasploit Cheat Sheet", url: "https://www.comparitech.com/net-admin/metasploit-cheat-sheet/" },
      { name: "IPv4 Subnet Cheat Sheet", url: "https://jodies.de/ipcalc" },
      { name: "Linux Command Line Cheat Sheet", url: "https://www.stationx.net/linux-command-line-cheat-sheet/" },
      { name: "Common Ports Cheat Sheet", url: "https://www.stationx.net/common-ports-cheat-sheet/" },
      { name: "AWK Command Cheat Sheet & Quick Reference", url: "https://quickref.me/awk" },
      { name: "PowerShell Docs", url: "https://learn.microsoft.com/powershell/" },
      { name: "example_hashes — hashcat wiki", url: "https://hashcat.net/wiki/doku.php?id=example_hashes" },
    ],
  },
  {
    title: "Useful Articles",
    icon: "FileText",
    links: [
      { name: "Manually Exploiting MS17-010 (python2 → python3)", url: g("Manually Exploiting MS17-010 python2 to python3") },
      { name: "Black Hat Ethical Hacking — Articles", url: "https://www.blackhatethicalhacking.com/articles/" },
      { name: "Hacking JWT Tokens: Bruteforcing Weak Signing Keys", url: g("Hacking JWT Tokens Bruteforcing Weak Signing Key") },
      { name: "Follina — MSDT Remote Code Execution", url: g("microsoft-office-remote-code-execution-follina-msdt") },
      { name: "Digital Forensics Myanmar", url: g("Digital Forensics Myanmar blog") },
      { name: "Windows Artifacts Cheat-Sheet", url: g("Windows Artifacts Cheat-Sheet list of various Windows artifacts") },
      { name: "Linux Forensics — Useful Artifacts", url: g("Linux Forensics Some Useful Artifacts") },
      { name: "Windows Security Log Encyclopedia", url: "https://www.ultimatewindowssecurity.com/securitylog/encyclopedia/" },
      { name: "Shadow Copies and Shadow Copy Sets (Win32 apps)", url: "https://learn.microsoft.com/windows/win32/vss/shadow-copies-and-shadow-copy-sets" },
      { name: "It's All Fun and Games Until Ransomware Deletes the Shadow Copies", url: g("It's all fun and games until ransomware deletes the shadow copies") },
      { name: "What Is a Shadow Copy and How to Recover Files Using It", url: g("what is a shadow copy and how to recover files using it") },
      { name: "iRed.team", url: "https://www.ired.team/" },
      { name: "TheBinaryHick.blog", url: "https://thebinaryhick.blog/" },
      { name: "mac4n6.com", url: "https://www.mac4n6.com/" },
    ],
  },
  {
    title: "News",
    icon: "Newspaper",
    links: [
      { name: "BleepingComputer", url: "https://www.bleepingcomputer.com/" },
      { name: "The Hacker News", url: "https://thehackernews.com/" },
      { name: "Infosec Resources", url: "https://resources.infosecinstitute.com/" },
      { name: "Microsoft Threat Intelligence", url: "https://www.microsoft.com/en-us/security/blog/microsoft-threat-intelligence/" },
      { name: "CrowdStrike Blog", url: "https://www.crowdstrike.com/blog/" },
      { name: "The Red Canary Blog", url: "https://redcanary.com/blog/" },
      { name: "Unit 42 (Palo Alto Networks)", url: "https://unit42.paloaltonetworks.com/" },
    ],
  },
  {
    title: "Email",
    icon: "Mail",
    links: [
      { name: "mha.azurewebsites.net", url: "https://mha.azurewebsites.net/" },
      { name: "Emkei's Fake Mailer", url: "https://emkei.cz/" },
      { name: "Thunderbird", url: "https://www.thunderbird.net/" },
    ],
  },
  {
    title: "CTF Useful Links",
    icon: "Puzzle",
    links: [
      { name: "Insecam", url: "http://www.insecam.org/" },
      { name: "spammimic — decode", url: "https://www.spammimic.com/decode.shtml" },
      { name: "Exif.tools", url: "https://exif.tools/" },
      { name: "Stegseek", url: "https://github.com/RickdeJager/stegseek" },
      { name: "zardus/ctf-tools", url: "https://github.com/zardus/ctf-tools" },
      { name: "decalage2/oletools Wiki (mraptor)", url: "https://github.com/decalage2/oletools/wiki/mraptor" },
      { name: "CFReDS — NIST", url: "https://cfreds.nist.gov/" },
      { name: "CTF Write-Ups", url: "https://github.com/ctfs/write-ups" },
      { name: "Malware-Traffic-Analysis.net", url: "https://www.malware-traffic-analysis.net/" },
      { name: "Applied Network Defense — Courses", url: "https://appliednetworkdefense.com/" },
      { name: "Seconds to HH:MM:SS Time Calculator", url: "https://www.calculatorsoup.com/calculators/time/seconds-to-hours-minutes-seconds.php" },
      { name: "DFIR — The Definitive Compendium Project", url: "https://aboutdfir.com/" },
      { name: "WhatsMyName Web", url: "https://whatsmyname.app/" },
      { name: "CalcResult", url: "https://calcresult.com/" },
      { name: "DTMF Detection Demo", url: g("DTMF detection demo online") },
      { name: "Spam Message Generator", url: "https://www.spammimic.com/" },
      { name: "Twin Hex Cipher", url: g("twin hex cipher tool") },
      { name: "Steganography Tools", url: "https://futureboy.us/stegano/" },
      { name: "Aperi'Solve", url: "https://aperisolve.fr/" },
      { name: "Bellingcat's Online Investigation Toolkit", url: "https://bit.ly/bcattool" },
      { name: "KeeWeb", url: "https://keeweb.info/" },
      { name: "Imgur", url: "https://imgur.com/" },
      { name: "YouTube Metadata", url: "https://mattw.io/youtube-metadata/" },
      { name: "OCLC WorldCat Gateway", url: "https://worldcat.org/" },
      { name: "Sherlock Project (username OSINT)", url: "https://github.com/sherlock-project/sherlock" },
      { name: "Reverse Video Search", url: g("reverse video search online free") },
      { name: "StegCloak", url: "https://stegcloak.surge.sh/" },
      { name: "Search CTF Writeups and Solutions", url: "https://ctf.wtf/" },
      { name: "TikTok Video Data Extractor", url: g("tiktok video data extractor tool") },
      { name: "Ciphers and Codes (dCode)", url: "https://www.dcode.fr/" },
      { name: "Arkham Intelligence", url: "https://platform.arkhamintelligence.com/" },
      { name: "Unfurl", url: "https://dfir.blog/unfurl/" },
      { name: "File Signatures (Gary Kessler)", url: "https://www.garykessler.net/library/file_sigs.html" },
      { name: "Unix Timestamp Converter", url: "https://www.unixtimestamp.com/" },
      { name: "User Agents Database", url: "https://useragents.io/" },
      { name: "Twitter ID Finder", url: "https://tweeterid.com/" },
      { name: "TPC to Map coordinates converter", url: g("TPC to map coordinates converter tool") },
      { name: "Gravatar", url: "https://gravatar.com/" },
      { name: "GeoHints", url: "https://geohints.com/" },
      { name: "Plonkit.net", url: "https://www.plonkit.net/" },
      { name: "GeoTips — Tips and Tricks for GeoGuessr", url: "https://geotips.net/" },
    ],
  },
  {
    title: "IOCs / Intels",
    icon: "Radar",
    links: [
      { name: "sophoslabs/IoCs", url: "https://github.com/sophoslabs/IoCs" },
      { name: "Microsoft Security Response Center", url: "https://msrc.microsoft.com/" },
      { name: "Have I Been Pwned?", url: "https://haveibeenpwned.com/" },
      { name: "Threat Intel Blogs Collection — himynamesdave", url: "https://github.com/himynamesdave/threat-intel-blogs" },
    ],
  },
  {
    title: "Playbooks",
    icon: "BookMarked",
    links: [
      { name: "Incident Response Plan Template (counteractive)", url: "https://github.com/counteractive/incident-response-plan-template" },
      { name: "IncidentResponse.org", url: "https://www.incidentresponse.org/" },
    ],
  },
  {
    title: "Other's Collection",
    icon: "FolderOpen",
    links: [
      { name: "DFM-SM-OSINT", url: g("DFM-SM-OSINT collection start.me") },
      { name: "Forensics Collection", url: g("digital forensics resource collection start.me") },
    ],
  },
]

export const hubStats = {
  categories: hubCategories.length,
  links: hubCategories.reduce((sum, c) => sum + c.links.length, 0) + featuredResources.length,
}
